# Puff-duration agreement: Pearson correlation + Bland-Altman analysis.
#
# Merges the two previously separate, ad hoc analyses --
# script_correlation_avg_hit_duration.py (Pearson r, participant-level trend)
# and Script_Bland_Altman.py (bias / limits of agreement / proportional
# bias) -- into one script, and rebuilds both directly from Script1's
# verified per-participant pipeline (imported unmodified) instead of from
# Participant_Summary.xlsx / Reconciled_Detection_Metrics_Summary_8_5_2026.xlsx.
#
# This matters because Participant_Summary.xlsx (the source of the
# manuscript's "2.53 +/- 0.83 s / 2.00 +/- 0.59 s" duration figures) was
# generated by an older/different pipeline than the now-verified Script1 --
# its per-participant durations differ from a fresh Script1 run by a small,
# consistent offset (e.g. FRIENDS2076 camera avg puff duration: 2.736 s in
# Participant_Summary.xlsx vs 2.776 s from Script1). Rebuilding from Script1
# directly means these numbers are reproducible from source data alone.
#
# Duration definition used: HITS ONLY -- Avg Hit Duration (Camera) vs Avg
# Hit Duration (FRIENDS), i.e. only puffs that were correctly matched
# between video and device.
#
# This is the only definition reported below (matching what the manuscript
# should report for both the correlation and the Bland-Altman analysis).
# "All puffs" (every annotated/detected puff, matched or not) was
# considered and rejected: Bland-Altman assumes each paired point is two
# measurements of the SAME event, which only holds for matched (hit)
# puffs. "All puffs" averages in FRIENDS' false-positive puff durations
# (no corresponding video event) and camera's missed-puff durations (no
# corresponding FRIENDS event) -- that conflates detection disagreement
# (already covered by the confusion-matrix precision/recall/F1 analysis)
# with duration-measurement disagreement, and is not a valid Bland-Altman
# comparison. See Codes/Script1_Puff_Analysis_Reconciled_Confusion_Matrix.py
# for the confusion matrix.

import os
import sys
import importlib.util

import numpy as np
import pandas as pd
from scipy import stats
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

THIS_DIR = os.path.dirname(os.path.abspath(__file__))
SCRIPT1_PATH = os.path.join(THIS_DIR, 'Script1_Puff_Analysis_Reconciled_Confusion_Matrix.py')

_spec = importlib.util.spec_from_file_location('script1_confusion_matrix', SCRIPT1_PATH)
script1 = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(script1)


def get_per_participant_durations(participant_dir):
    sub_folders = sorted([
        name for name in os.listdir(participant_dir)
        if os.path.isdir(os.path.join(participant_dir, name))
    ])
    rows = []
    for participant in sub_folders:
        res = script1.run_participant(participant, os.path.join(participant_dir, participant))
        rows.append({
            'Participant': participant,
            'Camera Avg Puff Duration': res['avg_camera_puff_duration'],
            'FRIENDS Avg Puff Duration': res['avg_friends_puff_duration'],
            'Avg Hit Duration (Camera)': res['avg_hit_duration_camera'],
            'Avg Hit Duration (FRIENDS)': res['avg_hit_duration_friends'],
        })
    return pd.DataFrame(rows)


def analyze_pair(cam, fri, label):
    """Pearson correlation + Bland-Altman for one (camera, friends) duration pair."""
    cam = np.asarray(cam, dtype=float)
    fri = np.asarray(fri, dtype=float)
    n = len(cam)

    cam_mean, cam_sd = cam.mean(), cam.std(ddof=1)
    fri_mean, fri_sd = fri.mean(), fri.std(ddof=1)

    r_corr, p_corr = stats.pearsonr(cam, fri)

    diff = cam - fri  # video (camera) minus FRIENDS
    means = (cam + fri) / 2
    bias = diff.mean()
    sd_diff = diff.std(ddof=1)
    loa_lo = bias - 1.96 * sd_diff
    loa_hi = bias + 1.96 * sd_diff

    se_bias = sd_diff / np.sqrt(n)
    se_loa = np.sqrt(3 * sd_diff ** 2 / n)
    t_crit = stats.t.ppf(0.975, df=n - 1)
    bias_ci = t_crit * se_bias
    loa_ci = t_crit * se_loa

    r_prop, p_prop = stats.pearsonr(means, diff)
    slope, intercept, *_ = stats.linregress(means, diff)

    return {
        'label': label, 'n': n,
        'cam': cam, 'fri': fri, 'diff': diff, 'means': means,
        'cam_mean': cam_mean, 'cam_sd': cam_sd,
        'fri_mean': fri_mean, 'fri_sd': fri_sd,
        'r_corr': r_corr, 'p_corr': p_corr,
        'bias': bias, 'sd_diff': sd_diff,
        'loa_lo': loa_lo, 'loa_hi': loa_hi,
        'bias_ci': bias_ci, 'loa_ci': loa_ci,
        'r_prop': r_prop, 'p_prop': p_prop,
        'slope': slope, 'intercept': intercept,
    }


def print_report(res):
    print(f"\n{'=' * 70}")
    print(f"{res['label']}  (n = {res['n']})")
    print('=' * 70)
    print(f"  Camera : mean = {res['cam_mean']:.4f} s   SD = {res['cam_sd']:.4f} s")
    print(f"  FRIENDS: mean = {res['fri_mean']:.4f} s   SD = {res['fri_sd']:.4f} s")
    print(f"  Pearson r = {res['r_corr']:.4f}   p = {res['p_corr']:.3e}")
    print(f"  Bland-Altman: mean bias (Camera-FRIENDS) = {res['bias']:+.4f} s "
          f"(95% CI: {res['bias']-res['bias_ci']:+.4f} to {res['bias']+res['bias_ci']:+.4f})")
    print(f"  95% LoA: {res['loa_lo']:+.4f} to {res['loa_hi']:+.4f} s")
    print(f"  Proportional bias: r = {res['r_prop']:.4f}   p = {res['p_prop']:.4f}")
    p_str = '< 0.001' if res['p_corr'] < 0.001 else f"= {res['p_corr']:.3f}"
    manuscript_sentence = (
        f"Mean {res['label'].lower()} duration across participants was "
        f"{res['cam_mean']:.2f} \u00b1 {res['cam_sd']:.2f} s, compared to "
        f"{res['fri_mean']:.2f} \u00b1 {res['fri_sd']:.2f} s from FRIENDS "
        f"(mean \u00b1 SD). Participant-level means were strongly correlated "
        f"(r = {res['r_corr']:.2f}, p {p_str})."
    )
    print(f"\n  Manuscript-style sentence:\n  {manuscript_sentence}")


def plot_bland_altman(res, out_path, title_suffix=''):
    fig, ax = plt.subplots(figsize=(7, 5))
    ax.scatter(res['means'], res['diff'], color='steelblue', s=60, zorder=3, label='Participants')
    ax.axhline(res['bias'], color='black', linewidth=1.5, linestyle='-',
               label=f"Bias = {res['bias']:+.2f} s")
    ax.axhline(res['loa_hi'], color='crimson', linewidth=1.2, linestyle='--',
               label=f"+1.96 SD = {res['loa_hi']:+.2f} s")
    ax.axhline(res['loa_lo'], color='crimson', linewidth=1.2, linestyle='--',
               label=f"-1.96 SD = {res['loa_lo']:+.2f} s")
    ax.axhline(0, color='gray', linewidth=0.8, linestyle=':')

    ax.axhspan(res['bias'] - res['bias_ci'], res['bias'] + res['bias_ci'], color='black', alpha=0.08)
    ax.axhspan(res['loa_hi'] - res['loa_ci'], res['loa_hi'] + res['loa_ci'], color='crimson', alpha=0.08)
    ax.axhspan(res['loa_lo'] - res['loa_ci'], res['loa_lo'] + res['loa_ci'], color='crimson', alpha=0.08)

    x_line = np.linspace(res['means'].min(), res['means'].max(), 200)
    y_line = res['slope'] * x_line + res['intercept']
    ax.plot(x_line, y_line, color='darkorange', linewidth=1.4, linestyle='-.',
            label=f"Prop. bias fit (r={res['r_prop']:.2f}, p={res['p_prop']:.3f})")

    ax.set_xlabel('Mean of Camera and FRIENDS duration (s)', fontsize=11)
    ax.set_ylabel('Difference: Camera \u2212 FRIENDS (s)', fontsize=11)
    ax.set_title(f"Bland\u2013Altman Plot: Puff Duration{title_suffix}", fontsize=12)
    ax.legend(fontsize=8, loc='upper left')
    ax.grid(True, linestyle=':', alpha=0.4)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'  Saved: {out_path}')


def plot_correlation(res, out_path, title_suffix=''):
    fig, ax = plt.subplots(figsize=(6, 6))
    cam, fri = res['cam'], res['fri']
    ax.scatter(cam, fri, alpha=0.75, s=60, edgecolors='k', linewidth=0.5, color='#4C72B0')
    lim_lo = min(cam.min(), fri.min()) * 0.9
    lim_hi = max(cam.max(), fri.max()) * 1.05
    ax.plot([lim_lo, lim_hi], [lim_lo, lim_hi], 'k--', linewidth=1.3, label='Unity line (y = x)')
    slope, intercept, r, p, se = stats.linregress(cam, fri)
    x_line = np.linspace(lim_lo, lim_hi, 200)
    ax.plot(x_line, slope * x_line + intercept, color='firebrick', linewidth=2,
            label=f'Regression: y = {intercept:.2f} + {slope:.2f}x')
    ax.set_xlim(lim_lo, lim_hi)
    ax.set_ylim(lim_lo, lim_hi)
    ax.set_xlabel('Camera duration (s)', fontsize=11)
    ax.set_ylabel('FRIENDS duration (s)', fontsize=11)
    ax.set_title(f"Correlation: Camera vs FRIENDS{title_suffix}\nr = {res['r_corr']:.3f}, "
                 f"p = {res['p_corr']:.2e}", fontsize=12)
    ax.legend(fontsize=8)
    ax.grid(True, alpha=0.3)
    plt.tight_layout()
    plt.savefig(out_path, dpi=150, bbox_inches='tight')
    plt.close(fig)
    print(f'  Saved: {out_path}')


def main(participant_dir, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    df = get_per_participant_durations(participant_dir)

    result = analyze_pair(df['Avg Hit Duration (Camera)'], df['Avg Hit Duration (FRIENDS)'], 'Hits only')
    print_report(result)

    plot_bland_altman(result, os.path.join(out_dir, 'BlandAltman_PuffDuration.png'))
    plot_correlation(result, os.path.join(out_dir, 'Correlation_PuffDuration.png'))

    summary_df = pd.DataFrame([{
        'Duration definition': result['label'],
        'n': result['n'],
        'Camera mean (s)': round(result['cam_mean'], 4),
        'Camera SD (s)': round(result['cam_sd'], 4),
        'FRIENDS mean (s)': round(result['fri_mean'], 4),
        'FRIENDS SD (s)': round(result['fri_sd'], 4),
        'Pearson r': round(result['r_corr'], 4),
        'Pearson p': result['p_corr'],
        'BA mean bias (s)': round(result['bias'], 4),
        'BA bias 95% CI (+/-)': round(result['bias_ci'], 4),
        'BA LoA lower (s)': round(result['loa_lo'], 4),
        'BA LoA upper (s)': round(result['loa_hi'], 4),
        'Proportional bias r': round(result['r_prop'], 4),
        'Proportional bias p': round(result['p_prop'], 4),
    }])

    out_xlsx = os.path.join(out_dir, 'Duration_Correlation_BlandAltman.xlsx')
    with pd.ExcelWriter(out_xlsx) as writer:
        df.to_excel(writer, sheet_name='Per_Participant_Durations', index=False)
        summary_df.to_excel(writer, sheet_name='Summary', index=False)
        pd.DataFrame({'Note': [
            'Duration = Avg Hit Duration (Camera) vs Avg Hit Duration (FRIENDS): only puffs that were '
            'correctly matched between video and device (TP puffs). This is the only valid definition '
            'for a Bland-Altman agreement analysis, since each pair must be two measurements of the same '
            'event -- an "all puffs" comparison would mix in FRIENDS false-positive durations (no video '
            'counterpart) and camera missed-puff durations (no FRIENDS counterpart), conflating detection '
            'disagreement (already covered by the Script1 confusion matrix) with duration-measurement '
            'disagreement.',
            'Computed fresh from Script1_Puff_Analysis_Reconciled_Confusion_Matrix.py (imported unmodified), '
            'not from any pre-existing summary spreadsheet.',
            'Bland-Altman: bias = mean(Camera-FRIENDS); LoA = bias +/- 1.96*SD(diff); '
            'proportional bias = Pearson r between per-participant mean and difference.',
        ]}).to_excel(writer, sheet_name='Method', index=False)

    print(f'\nWritten: {out_xlsx}')
    return df, result


if __name__ == '__main__':
    Participant_Dir = r'C:\Users\claws\Documents\FRIENDS_UB_LAB\FRIENDS Paper Lab Data, Code and Results\Participant Data'
    Out_Dir = r'C:\Users\claws\Documents\FRIENDS_UB_LAB\FRIENDS Paper Lab Data, Code and Results\Results\Duration_Correlation_BlandAltman'
    if len(sys.argv) >= 3:
        Participant_Dir = sys.argv[1]
        Out_Dir = sys.argv[2]
    main(Participant_Dir, Out_Dir)
